### ISSUE TITLE
Update Block oss-release GPG Key from TBD one

### ISSUE THREAD

**Issue by ALRubinger** [block/ospo#17]
The one now being used:

```
[INFO] Loaded KeyId: 0x293D005E4DAF68D5A31A96F44CA6B792C4F48116, uids: [tbd-releases (GPG Key to sign TBD Releases) <releases@tbd.email>]
```

As seen: https://github.com/block/example-jvm-maven/actions/runs/11889729230/job/33127133221#step:5:3329

Make a Block one, upload the public key to a public keyserver (instructions in the internal GDoc we just ported passwords from) store in team vault, and update Block org GH Actions secrets for it.

Then @ALRubinger can test Sonatype compatibility by cutting new release of `example-jvm-maven`.

**Comment by finn-block** [comment]
This is now done and I re-ran that job ([logs](https://github.com/block/example-jvm-maven/actions/runs/11889729230/job/33160982627)):

```
[INFO] Loaded KeyId: 0x1D217F8475EEE9F19AB8DD6B793FD5751A0F0780, uids: [Block Open Source Releases <oss-releases@block.xyz>]
```
